// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VoxBox.Infrastructure.Migrations;

[DbContext(typeof(VoxBox.Infrastructure.Persistence.VoxBoxDbContext))]
[Migration("20251226143000_DropOldIntegerTables")]
partial class DropOldIntegerTables
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.1");
#pragma warning restore 612, 618
    }
}